import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { z } from 'astro/zod';
import { docsLoader, i18nLoader } from "@astrojs/starlight/loaders";
import { docsSchema, i18nSchema } from "@astrojs/starlight/schema";

export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
  blog: defineCollection({
    loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/blog" }),
    schema: ({ image }) => z.object({
      title: z.string(),
      description: z.string(),
      publishedAt: z.coerce.date(),
      updatedAt: z.coerce.date().optional(),
      author: z.string().default("Steel Team"),
      category: z.string().default("News"),
      featured: z.boolean().default(false),
      placeholder: z.boolean().default(false),
      socialImage: z.object({
        src: image(),
        alt: z.string().min(1),
      }).optional(),
    }),
  }),
  i18n: defineCollection({ loader: i18nLoader(), schema: i18nSchema({
      extend: z.object({
        langFlag: z.string().optional(),
        langName: z.string().optional(),
        searchPlaceholder: z.string().optional(),
        devWarningText: z.string().optional(),
        discordLabel: z.string().optional(),
        githubLabel: z.string().optional(),
        download: z.string().optional(),
        githubHref: z.string().optional(),
        version: z.string().optional(),
        latestVersion: z.string().optional(),
        needOlderVersion: z.string().optional(),
        viewPreviousVersions: z.string().optional(),
        olderVersions: z.string().optional(),
        forMinecraft: z.string().optional(),
        releasedDate: z.string().optional(),
        tracker: z.string().optional(),
        trackerLabel: z.string().optional(),

        // ── index page ────────────────────────────────────────────────
        "index.pillText": z.string().optional(),
        "index.subtitle": z.string().optional(),
        "index.mainCtaText": z.string().optional(),
        "index.secondCtaText": z.string().optional(),
        "index.chooseDocs.label": z.string().optional(),
        "index.chooseDocs.title": z.string().optional(),
        "index.chooseDocs.description": z.string().optional(),
        "index.chooseDocs.adminLabel": z.string().optional(),
        "index.chooseDocs.adminImageAlt": z.string().optional(),
        "index.chooseDocs.devLabel": z.string().optional(),
        "index.chooseDocs.devImageAlt": z.string().optional(),
        "index.community.heading": z.string().optional(),
        "index.community.headingHighlight": z.string().optional(),
        "index.community.descriptionBold1": z.string().optional(),
        "index.community.descriptionMiddle": z.string().optional(),
        "index.community.descriptionBold2": z.string().optional(),
        "index.community.descriptionAfter": z.string().optional(),
        "index.rotating.prefix": z.string().optional(),
        "index.rotating.count": z.string().optional(),
        "index.rotating.0": z.string().optional(),
        "index.rotating.1": z.string().optional(),
        "index.rotating.2": z.string().optional(),
        "index.rotating.3": z.string().optional(),
        "index.rotating.4": z.string().optional(),
        "index.rotating.5": z.string().optional(),
        "index.rotating.6": z.string().optional(),
        "index.rotating.7": z.string().optional(),
        "index.rotating.8": z.string().optional(),
        "index.rotating.9": z.string().optional(),
        "index.rotating.10": z.string().optional(),
        "index.rotating.11": z.string().optional(),
        "index.rotating.12": z.string().optional(),

        // ── tracker page ──────────────────────────────────────────────
        "tracker.title": z.string().optional(),
        "tracker.titleHighlight": z.string().optional(),
        "tracker.description": z.string().optional(),
        "tracker.note": z.string().optional(),
        "tracker.metaTitle": z.string().optional(),
        "tracker.metaDescription": z.string().optional(),

        // ── download page ─────────────────────────────────────────────
        "download.metaDescription": z.string().optional(),
        "download.badge": z.string().optional(),
        "download.hero.title": z.string().optional(),
        "download.hero.titleHighlight": z.string().optional(),
        "download.hero.subtitle": z.string().optional(),
        "download.latestBadge": z.string().optional(),
        "download.latestDescription": z.string().optional(),
        "download.choosePlatform": z.string().optional(),
        "download.installHint": z.string().optional(),
        "download.installHintLink": z.string().optional(),
        "download.previousReleases": z.string().optional(),
        "download.browseOlder": z.string().optional(),
        "download.browseOlderPlural": z.string().optional(),
        "download.noReleases.title": z.string().optional(),
        "download.noReleases.body": z.string().optional(),
        "download.forMinecraft": z.string().optional(),

        // ── blog page ─────────────────────────────────────────────────
        "blog.metaTitle": z.string().optional(),
        "blog.metaDescription": z.string().optional(),
        "blog.badge": z.string().optional(),
        "blog.title": z.string().optional(),
        "blog.titleHighlight": z.string().optional(),
        "blog.subtitle": z.string().optional(),
        "blog.featured": z.string().optional(),
        "blog.readArticle": z.string().optional(),
        "blog.latestPosts": z.string().optional(),
        "blog.allPosts": z.string().optional(),
        "blog.backToBlog": z.string().optional(),
        "blog.minRead": z.string().optional(),
        "blog.placeholder.title": z.string().optional(),
        "blog.placeholder.body": z.string().optional(),
        "blog.footer": z.string().optional(),
      }),
  }) }),
};
